# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: local
  hooks:
  - id: jsonnetfmt
    name: jsonnetfmt
    entry: jsonnetfmt -i
    language: system
    files: "\\.(?:jsonnet|libsonnet)"
  - id: tkfmt
    name: tkfmt
    entry: tk fmt
    language: system
    files: "\\.(?:jsonnet|libsonnet)"
