name: Jsonnet tests

on:
  push:
    branches:
      - "*"

jobs:
  crossplane:
    name: Test crossplane libs
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on

    steps:
      # Setup
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - run: |
          go install github.com/google/go-jsonnet/cmd/jsonnet@latest
          go install github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb@latest

      # Install dependencies
      - run: cd crossplane && ~/go/bin/jb install

      # Run tests
      - id: run-tests
        run: ~/go/bin/jsonnet -J crossplane -J crossplane/vendor tests/test_aws-utils.jsonnet

